---
driver:
  name: dokken
  chef_version: latest
  privileged: true #Because Docker/SystemD

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: centos-7
    driver: 
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      ports:
        - 9080:80

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
